version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: mapsketch-pgsql-database
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - postgres_storage:/data
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"]
      interval: 5s
      retries: 5
      start_period: 10s
    networks:
      - shared_network

  mapsketch-api:
    build: .
    env_file:
      - .env
    image: mapsketch-api
    container_name: mapsketch-api
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - shared_network

volumes:
  postgres_storage:

networks:
  shared_network:
    driver: bridge
